import = ['~/.config/alacritty/theme.toml']
[font]
size = 12.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[window]
opacity = 0.9
decorations = "Full"
